# ╔═════════════════════════════════════════════════════════════════════════════════════════════════
# ║     config.yml
# ╠═════════════════════════════════════════════════════════════════════════════════════════════════
# ║     Created: 02.02.2025
# ║
# ║     Copyright (c) 2025 James Dooley <james@dooley.ch>
# ║
# ║     History:
# ║     02.02.2025: Initial version
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════

simfin:
  regions:
    - us
    - cn
    - de
  time-frames:
    - annual
    - quarterly
    - ttm
  companies:
    - standard
    - banks
    - insurance
  others:
    - markets
    - industries

logging:
  file_name: simfin.log
  level: debug # Valid values: unknown, fatal, error, warn, info, debug

database:
  database: sat_company_data_dev
  user: sat_dev_user
  password: dev*123
